@startuml
actor client as client
participant auth.php as auth #yellow
database SGBD as bdd #green

client -> auth: JSON{code=1,login, password}
auth -> bdd: check user privileges

alt success: user exists
bdd -[#green]> auth: user's level of privileges
auth -> auth: Generating JWT token {login, privileges}
auth -[#green]> client: HTTP=200 {JWT token}

else failure: user doesn't exist
bdd -[#red]> auth: error
auth -[#red]> client: HTTP=403
end

@enduml
